name: Publish Release
on:
  push:
    paths:
      - '**.cff'
    branches:
      - 'main'
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.head_commit.message }}
        token: ${{ secrets.RELEASE_TOKEN }}
